export const drinkInfo = [
    {
        "drink_id": 1,
        "drink_price": 7.5,
        "drink_hunger": 3,
        "drink_mood": 37,
        "drink_thirsty": 45,
        "drink_name": "雷碧",
        "drink_pic_path": "雷碧.png",
        "drink_endu": 5,
        "drink_exp": 3,
        "drink_health": -1
    },
    {
        "drink_id": 2,
        "drink_price": 7.5,
        "drink_hunger": 5,
        "drink_mood": 2,
        "drink_thirsty": 35,
        "drink_name": "维他奶",
        "drink_pic_path": "维他奶.png",
        "drink_endu": 15,
        "drink_exp": 10,
        "drink_health": 1
    },
    {
        "drink_id": 3,
        "drink_price": 8.5,
        "drink_hunger": 3,
        "drink_mood": 37,
        "drink_thirsty": 40,
        "drink_name": "盐汽水",
        "drink_pic_path": "盐汽水.png",
        "drink_endu": 15,
        "drink_exp": 10,
        "drink_health": -0.5
    },
    {
        "drink_id": 4,
        "drink_price": 11.5,
        "drink_hunger": 4,
        "drink_mood": 25,
        "drink_thirsty": 50,
        "drink_name": "椰汁",
        "drink_pic_path": "椰汁.png",
        "drink_endu": 15,
        "drink_exp": 10,
        "drink_health": 2
    },
    {
        "drink_id": 5,
        "drink_price": 9.5,
        "drink_hunger": 4,
        "drink_mood": 7,
        "drink_thirsty": 40,
        "drink_name": "果汁",
        "drink_pic_path": "果汁.png",
        "drink_endu": 10,
        "drink_exp": 10,
        "drink_health": 3
    },
    {
        "drink_id": 6,
        "drink_price": 9,
        "drink_hunger": 2,
        "drink_mood": 50,
        "drink_thirsty": 50,
        "drink_name": "可乐",
        "drink_pic_path": "可乐.png",
        "drink_endu": 10,
        "drink_exp": 5,
        "drink_health": -1
    },
    {
        "drink_id": 7,
        "drink_price": 14.5,
        "drink_hunger": 1,
        "drink_mood": 12,
        "drink_thirsty": 60,
        "drink_name": "凉茶",
        "drink_pic_path": "凉茶.png",
        "drink_endu": 10,
        "drink_exp": 20,
        "drink_health": 5
    },
    {
        "drink_id": 8,
        "drink_price": 7,
        "drink_hunger": 5,
        "drink_mood": 2,
        "drink_thirsty": 40,
        "drink_name": "ab钙奶",
        "drink_pic_path": "ab钙奶.png",
        "drink_endu": 10,
        "drink_exp": 5,
        "drink_health": 1
    },
    {
        "drink_id": 9,
        "drink_price": 14,
        "drink_hunger": 3,
        "drink_mood": 25,
        "drink_thirsty": 20,
        "drink_name": "黄牛",
        "drink_pic_path": "黄牛.png",
        "drink_endu": 85,
        "drink_exp": 80,
        "drink_health": -1
    },
    {
        "drink_id": 10,
        "drink_price": 13.5,
        "drink_hunger": 3,
        "drink_mood": 20,
        "drink_thirsty": 20,
        "drink_name": "能量饮料",
        "drink_pic_path": "能量饮料.png",
        "drink_endu": 80,
        "drink_exp": 140,
        "drink_health": -5
    },
    {
        "drink_id": 11,
        "drink_price": 13,
        "drink_hunger": 3,
        "drink_mood": 25,
        "drink_thirsty": 20,
        "drink_name": "大鹏特饮",
        "drink_pic_path": "大鹏特饮.png",
        "drink_endu": 85,
        "drink_exp": 60,
        "drink_health": -1
    },
    {
        "drink_id": 12,
        "drink_price": 0,
        "drink_hunger": 75,
        "drink_mood": -100,
        "drink_thirsty": 75,
        "drink_name": "地球",
        "drink_pic_path": "地球.png",
        "drink_endu": -50,
        "drink_exp": -100,
        "drink_health": 0
    }
]
