export const foodInfo = [
    {
        "food_id": 1,
        "food_mood": 100,
        "food_thirsty": 100,
        "food_name": "辣子鸡",
        "food_price": 43,
        "food_hunger": 120,
        "food_pic_path": "辣子鸡.png",
        "food_endu": 100,
        "food_exp": 150,
        "food_health": 0
    },
    {
        "food_id": 2,
        "food_mood": 75,
        "food_thirsty": 0,
        "food_name": "麻婆豆腐",
        "food_price": 35,
        "food_hunger": 110,
        "food_pic_path": "麻婆豆腐.png",
        "food_endu": 100,
        "food_exp": 100,
        "food_health": 0
    },
    {
        "food_id": 3,
        "food_mood": 50,
        "food_thirsty": 0,
        "food_name": "鸡翅",
        "food_price": 24.5,
        "food_hunger": 75,
        "food_pic_path": "鸡翅.png",
        "food_endu": 100,
        "food_exp": 30,
        "food_health": 0
    },
    {
        "food_id": 4,
        "food_mood": 125,
        "food_thirsty": 30,
        "food_name": "香煎牛仔骨",
        "food_price": 83,
        "food_hunger": 160,
        "food_pic_path": "香煎牛仔骨.png",
        "food_endu": 120,
        "food_exp": 300,
        "food_health": 10
    },
    {
        "food_id": 5,
        "food_mood": 25,
        "food_thirsty": 0,
        "food_name": "面包",
        "food_price": 21,
        "food_hunger": 100,
        "food_pic_path": "面包.png",
        "food_endu": 50,
        "food_exp": 0,
        "food_health": 0
    },
    {
        "food_id": 6,
        "food_mood": 37,
        "food_thirsty": 0,
        "food_name": "酿豆腐",
        "food_price": 27,
        "food_hunger": 80,
        "food_pic_path": "酿豆腐.png",
        "food_endu": 100,
        "food_exp": 75,
        "food_health": 0
    },
    {
        "food_id": 7,
        "food_mood": 87,
        "food_thirsty": 50,
        "food_name": "酸菜鱼",
        "food_price": 42,
        "food_hunger": 110,
        "food_pic_path": "酸菜鱼.png",
        "food_endu": 120,
        "food_exp": 150,
        "food_health": 0
    },
    {
        "food_id": 8,
        "food_mood": 100,
        "food_thirsty": 30,
        "food_name": "西冷牛排",
        "food_price": 74.5,
        "food_hunger": 140,
        "food_pic_path": "西冷牛排.png",
        "food_endu": 120,
        "food_exp": 250,
        "food_health": 15
    },
    {
        "food_id": 9,
        "food_mood": 75,
        "food_thirsty": 0,
        "food_name": "芝士焗虾",
        "food_price": 30,
        "food_hunger": 70,
        "food_pic_path": "芝士焗虾.png",
        "food_endu": 80,
        "food_exp": 125,
        "food_health": 0
    },
    {
        "food_id": 10,
        "food_mood": 12,
        "food_thirsty": 0,
        "food_name": "臭豆腐",
        "food_price": 19.5,
        "food_hunger": 55,
        "food_pic_path": "臭豆腐.png",
        "food_endu": 100,
        "food_exp": 50,
        "food_health": 0
    },
    {
        "food_id": 11,
        "food_mood": 75,
        "food_thirsty": 80,
        "food_name": "罗宋汤",
        "food_price": 36.5,
        "food_hunger": 110,
        "food_pic_path": "罗宋汤.png",
        "food_endu": 100,
        "food_exp": 100,
        "food_health": 0
    },
    {
        "food_id": 12,
        "food_mood": 75,
        "food_thirsty": 30,
        "food_name": "纸包鸡",
        "food_price": 29.5,
        "food_hunger": 75,
        "food_pic_path": "纸包鸡.png",
        "food_endu": 85,
        "food_exp": 100,
        "food_health": 0
    },
    {
        "food_id": 13,
        "food_mood": 75,
        "food_thirsty": 30,
        "food_name": "红烧狮子头",
        "food_price": 39,
        "food_hunger": 90,
        "food_pic_path": "红烧狮子头.png",
        "food_endu": 120,
        "food_exp": 150,
        "food_health": 1
    },
    {
        "food_id": 14,
        "food_mood": 75,
        "food_thirsty": 50,
        "food_name": "红烧牛肉",
        "food_price": 47,
        "food_hunger": 130,
        "food_pic_path": "红烧牛肉.png",
        "food_endu": 140,
        "food_exp": 150,
        "food_health": 1
    },
    {
        "food_id": 15,
        "food_mood": 75.00,
        "food_thirsty": 40.00,
        "food_name": "盐焗鸡",
        "food_price": 36.50,
        "food_hunger": 90.00,
        "food_pic_path": "盐焗鸡.png",
        "food_endu": 100.00,
        "food_exp": 150.00,
        "food_health": 0.00
    },
    {
        "food_id": 16,
        "food_mood": 50.00,
        "food_thirsty": 40.00,
        "food_name": "番茄意面",
        "food_price": 36.00,
        "food_hunger": 110.00,
        "food_pic_path": "番茄意面.png",
        "food_endu": 100.00,
        "food_exp": 100.00,
        "food_health": 1.00
    },
    {
        "food_id": 17,
        "food_mood": 100.00,
        "food_thirsty": 30.00,
        "food_name": "煎西冷牛排",
        "food_price": 71.00,
        "food_hunger": 150.00,
        "food_pic_path": "煎西冷牛排.png",
        "food_endu": 140.00,
        "food_exp": 225.00,
        "food_health": 15.00
    },
    {
        "food_id": 18,
        "food_mood": 75.00,
        "food_thirsty": 30.00,
        "food_name": "烧鹅",
        "food_price": 39.50,
        "food_hunger": 100.00,
        "food_pic_path": "烧鹅.png",
        "food_endu": 120.00,
        "food_exp": 150.00,
        "food_health": 0.00
    },
    {
        "food_id": 19,
        "food_mood": 50.00,
        "food_thirsty": 10.00,
        "food_name": "炸鸡腿",
        "food_price": 16.00,
        "food_hunger": 40.00,
        "food_pic_path": "炸鸡腿.png",
        "food_endu": 40.00,
        "food_exp": 50.00,
        "food_health": -2.00
    },
    {
        "food_id": 20,
        "food_mood": 12.00,
        "food_thirsty": 35.00,
        "food_name": "沙拉",
        "food_price": 39.00,
        "food_hunger": 80.00,
        "food_pic_path": "沙拉.png",
        "food_endu": 80.00,
        "food_exp": 150.00,
        "food_health": 10.00
    },
    {
        "food_id": 21,
        "food_mood": 50.00,
        "food_thirsty": 10.00,
        "food_name": "汉堡",
        "food_price": 20.50,
        "food_hunger": 60.00,
        "food_pic_path": "汉堡.png",
        "food_endu": 60.00,
        "food_exp": 50.00,
        "food_health": -2.00
    },
    {
        "food_id": 22,
        "food_mood": 62.00,
        "food_thirsty": 30.00,
        "food_name": "梅菜扣肉",
        "food_price": 35.50,
        "food_hunger": 100.00,
        "food_pic_path": "梅菜扣肉.png",
        "food_endu": 100.00,
        "food_exp": 125.00,
        "food_health": 0.00
    },
    {
        "food_id": 23,
        "food_mood": 50.00,
        "food_thirsty": 10.00,
        "food_name": "披萨",
        "food_price": 36.50,
        "food_hunger": 100.00,
        "food_pic_path": "披萨.png",
        "food_endu": 100.00,
        "food_exp": 150.00,
        "food_health": -1.50
    },
    {
        "food_id": 24,
        "food_mood": 37.00,
        "food_thirsty": 10.00,
        "food_name": "南瓜吐司",
        "food_price": 27.50,
        "food_hunger": 100.00,
        "food_pic_path": "南瓜吐司.png",
        "food_endu": 80.00,
        "food_exp": 50.00,
        "food_health": 0.00
    },
    {
        "food_id": 25,
        "food_mood": 75.00,
        "food_thirsty": 30.00,
        "food_name": "华夫饼",
        "food_price": 29.50,
        "food_hunger": 80.00,
        "food_pic_path": "华夫饼.png",
        "food_endu": 100.00,
        "food_exp": 70.00,
        "food_health": 0.00
    },
    {
        "food_id": 26,
        "food_mood": 75.00,
        "food_thirsty": 50.00,
        "food_name": "东坡肘子",
        "food_price": 36.50,
        "food_hunger": 85.00,
        "food_pic_path": "东坡肘子.png",
        "food_endu": 100.00,
        "food_exp": 150.00,
        "food_health": 1.00
    },
    {
        "food_id": 27,
        "food_mood": 37.00,
        "food_thirsty": 30.00,
        "food_name": "三明治",
        "food_price": 25.00,
        "food_hunger": 85.00,
        "food_pic_path": "三明治.png",
        "food_endu": 80.00,
        "food_exp": 50.00,
        "food_health": 0.00
    },
    {
        "food_id": 28,
        "food_mood": 25.00,
        "food_thirsty": 5.00,
        "food_name": "雪饼",
        "food_price": 6.00,
        "food_hunger": 15.00,
        "food_pic_path": "雪饼.png",
        "food_endu": 10.00,
        "food_exp": 10.00,
        "food_health": -1.00
    },
    {
        "food_id": 29,
        "food_mood": 12.00,
        "food_thirsty": -2.00,
        "food_name": "软糖",
        "food_price": 3.50,
        "food_hunger": 12.00,
        "food_pic_path": "软糖.png",
        "food_endu": 5.00,
        "food_exp": 10.00,
        "food_health": -1.00
    },
    {
        "food_id": 30,
        "food_mood": 12.00,
        "food_thirsty": -5.00,
        "food_name": "薯片",
        "food_price": 6.00,
        "food_hunger": 28.00,
        "food_pic_path": "薯片.png",
        "food_endu": 10.00,
        "food_exp": 10.00,
        "food_health": -1.50
    },
    {
        "food_id": 31,
        "food_mood": 4.00,
        "food_thirsty": -5.00,
        "food_name": "花生米",
        "food_price": 4.00,
        "food_hunger": 20.00,
        "food_pic_path": "花生米.png",
        "food_endu": 20.00,
        "food_exp": 5.00,
        "food_health": 0.00
    },
    {
        "food_id": 32,
        "food_mood": 5.00,
        "food_thirsty": 15.00,
        "food_name": "老冰棍",
        "food_price": 4.00,
        "food_hunger": 5.00,
        "food_pic_path": "老冰棍.png",
        "food_endu": 15.00,
        "food_exp": 10.00,
        "food_health": 0.00
    },
    {
        "food_id": 33,
        "food_mood": 12.00,
        "food_thirsty": 15.00,
        "food_name": "绿色心情",
        "food_price": 3.00,
        "food_hunger": 5.00,
        "food_pic_path": "绿色心情.png",
        "food_endu": 5.00,
        "food_exp": 5.00,
        "food_health": 0.00
    },
    {
        "food_id": 34,
        "food_mood": 37.00,
        "food_thirsty": -2.00,
        "food_name": "瓜子",
        "food_price": 8.50,
        "food_hunger": 26.00,
        "food_pic_path": "瓜子.png",
        "food_endu": 30.00,
        "food_exp": 5.00,
        "food_health": 0.00
    },
    {
        "food_id": 35,
        "food_mood": 37.00,
        "food_thirsty": 0.00,
        "food_name": "猪肉脯",
        "food_price": 14.00,
        "food_hunger": 48.00,
        "food_pic_path": "猪肉脯.png",
        "food_endu": 40.00,
        "food_exp": 15.00,
        "food_health": 0.00
    },
    {
        "food_id": 36,
        "food_mood": 25.00,
        "food_thirsty": -1.00,
        "food_name": "牛板筋",
        "food_price": 3.00,
        "food_hunger": 8.00,
        "food_pic_path": "牛板筋.png",
        "food_endu": 10.00,
        "food_exp": 10.00,
        "food_health": -1.00
    },
    {
        "food_id": 37,
        "food_mood": 37.00,
        "food_thirsty": -2.00,
        "food_name": "牛扎糖",
        "food_price": 4.50,
        "food_hunger": 8.00,
        "food_pic_path": "牛扎糖.png",
        "food_endu": 10.00,
        "food_exp": 10.00,
        "food_health": 0.00
    },
    {
        "food_id": 38,
        "food_mood": 25.00,
        "food_thirsty": -5.00,
        "food_name": "爆米花",
        "food_price": 8.00,
        "food_hunger": 30.00,
        "food_pic_path": "爆米花.png",
        "food_endu": 40.00,
        "food_exp": 10.00,
        "food_health": -1.00
    },
    {
        "food_id": 39,
        "food_mood": 30.00,
        "food_thirsty": -2.00,
        "food_name": "火腿肠",
        "food_price": 8.50,
        "food_hunger": 38.00,
        "food_pic_path": "火腿肠.png",
        "food_endu": 40.00,
        "food_exp": 5.00,
        "food_health": -0.50
    },
    {
        "food_id": 40,
        "food_mood": 42.00,
        "food_thirsty": -1.00,
        "food_name": "泡泡糖",
        "food_price": 4.50,
        "food_hunger": 5.00,
        "food_pic_path": "泡泡糖.png",
        "food_endu": 5.00,
        "food_exp": 15.00,
        "food_health": 0.00
    },
    {
        "food_id": 41,
        "food_mood": 5.00,
        "food_thirsty": -2.00,
        "food_name": "核桃仁",
        "food_price": 9.50,
        "food_hunger": 5.00,
        "food_pic_path": "核桃仁.png",
        "food_endu": 20.00,
        "food_exp": 40.00,
        "food_health": 0.50
    },
    {
        "food_id": 42,
        "food_mood": 20.00,
        "food_thirsty": 10.00,
        "food_name": "散射雪糕",
        "food_price": 7.00,
        "food_hunger": 20.00,
        "food_pic_path": "散射雪糕.png",
        "food_endu": 10.00,
        "food_exp": 5.00,
        "food_health": 0.00
    },
    {
        "food_id": 43,
        "food_mood": 20.00,
        "food_thirsty": -2.00,
        "food_name": "戒指糖",
        "food_price": 2.50,
        "food_hunger": 10.00,
        "food_pic_path": "戒指糖.png",
        "food_endu": 20.00,
        "food_exp": 5.00,
        "food_health": -0.50
    },
    {
        "food_id": 44,
        "food_mood": 37.00,
        "food_thirsty": -5.00,
        "food_name": "巧克力",
        "food_price": 10.50,
        "food_hunger": 38.00,
        "food_pic_path": "巧克力.png",
        "food_endu": 30.00,
        "food_exp": 10.00,
        "food_health": 0.00
    },
    {
        "food_id": 45,
        "food_mood": 12.00,
        "food_thirsty": 5.00,
        "food_name": "小布丁",
        "food_price": 4.00,
        "food_hunger": 10.00,
        "food_pic_path": "小布丁.png",
        "food_endu": 10.00,
        "food_exp": 10.00,
        "food_health": 0.00
    },
    {
        "food_id": 46,
        "food_mood": 25.00,
        "food_thirsty": -2.00,
        "food_name": "娃仔小馒头",
        "food_price": 5.00,
        "food_hunger": 12.00,
        "food_pic_path": "娃仔小馒头.png",
        "food_endu": 15.00,
        "food_exp": 10.00,
        "food_health": -0.50
    },
    {
        "food_id": 47,
        "food_mood": 37.00,
        "food_thirsty": -2.00,
        "food_name": "奶糖",
        "food_price": 6.00,
        "food_hunger": 15.00,
        "food_pic_path": "奶糖.png",
        "food_endu": 8.00,
        "food_exp": 15.00,
        "food_health": 0.00
    },
    {
        "food_id": 48,
        "food_mood": 17.00,
        "food_thirsty": -2.00,
        "food_name": "奶片",
        "food_price": 3.00,
        "food_hunger": 8.00,
        "food_pic_path": "奶片.png",
        "food_endu": 8.00,
        "food_exp": 10.00,
        "food_health": 0.00
    },
    {
        "food_id": 49,
        "food_mood": 50.00,
        "food_thirsty": 5.00,
        "food_name": "冰激凌",
        "food_price": 10.00,
        "food_hunger": 24.00,
        "food_pic_path": "冰激凌.png",
        "food_endu": 40.00,
        "food_exp": 5.00,
        "food_health": -0.50
    },
    {
        "food_id": 50,
        "food_mood": 20.00,
        "food_thirsty": -10.00,
        "food_name": "土力架",
        "food_price": 17.50,
        "food_hunger": 80.00,
        "food_pic_path": "土力架.png",
        "food_endu": 80.00,
        "food_exp": 5.00,
        "food_health": 0.00
    },
    {
        "food_id": 50,
        "food_mood": 20.00,
        "food_thirsty": -10.00,
        "food_name": "土力架",
        "food_price": 17.50,
        "food_hunger": 80.00,
        "food_pic_path": "土力架.png",
        "food_endu": 80.00,
        "food_exp": 5.00,
        "food_health": 0.00
    },
    {
        "food_id": 51,
        "food_mood": 5.00,
        "food_thirsty": -20.00,
        "food_name": "压缩饼干",
        "food_price": 18.50,
        "food_hunger": 100.00,
        "food_pic_path": "压缩饼干.png",
        "food_endu": 60.00,
        "food_exp": 5.00,
        "food_health": 0.00
    }
]
